### ISSUE TITLE
Adapt dbt_project.yml to dbt version 0.17.x

### ISSUE THREAD

**Issue by olivierdupuis** [rittmananalytics/ra_data_warehouse#11]
The latest release of dbt introduces changes to dbt_project.yml that need to be reflected in the framework. 

https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0/

Essentially, two changes need to be made:
- Add the `config-version` 
- Move all vars to their top-level `vars:` dictionary.

That second change involves more refactoring as variables cannot be scoped to a folder level. We will need to rename the variables to a unique name and use those unique var names in the models.

┆Issue is synchronized with this [Jira Task](https://rittmananalytics.atlassian.net/browse/RADW-9) by [Unito](https://www.unito.io/learn-more)

**Comment by markrittman** [comment]
Done and merged into master with this PR https://github.com/rittmananalytics/ra_data_warehouse/pull/12

**Comment by markrittman** [comment]
Issue addressed with this PR https://github.com/rittmananalytics/ra_data_warehouse/pull/12
