### ISSUE TITLE
Use dbt_utils.surrogate_key to generate primary and foreign keys

### ISSUE THREAD

**Issue by olivierdupuis** [rittmananalytics/ra_data_warehouse#4]
The framework currently uses `GENERATE_UUID()`, but in order to control the keys associated to our entity tables, it would be useful to use the `surrogate_key` function from the `dbt_utils` package. 

This allows us to "seed" the generation of unique ids with fixed field values, such as a source's natural key. Using `surrogate_key` allows us to generate foreign keys that have the same value as its relationship's primary key, enabling joins to be made.

Example...

```
select
    {{ dbt_utils.surrogate_key(
      ['transaction_platform_natural_key']
    ) }} as platform_asset_transaction_pk,
    {{ dbt_utils.surrogate_key(
      ['user_platform_natural_key']
    ) }} as platform_user_fk...
```

┆Issue is synchronized with this [Jira Task](https://rittmananalytics.atlassian.net/browse/RADW-2) by [Unito](https://www.unito.io/learn-more)

**Comment by markrittman** [comment]
Now done and present in the latest version of the repo
