### ISSUE TITLE
Support Segment as an ETL

### ISSUE THREAD

**Issue by olivierdupuis** [rittmananalytics/ra_data_warehouse#7]
Pre-stages models are for the most part only pulling data from either Stitch or Fivetran. But Segment can also be a pretty frequent alternative to those 2 services. The requirements here would be to add Segment as a 3rd alternative to the current staged models.

┆Issue is synchronized with this [Jira Task](https://rittmananalytics.atlassian.net/browse/RADW-5) by [Unito](https://www.unito.io/learn-more)

**Comment by markrittman** [comment]
done, and used for Facebooks Ads, Google Ads and Stripe in the current release of the repo.
