### ISSUE TITLE
Review staging models

### ISSUE THREAD

**Issue by olivierdupuis** [rittmananalytics/ra_data_warehouse#9]
There are a few issues with the staging models as they are right now. Some of those issues are preventing the out-of-the-box compilation of those models. They generally related to CTEs not closing correctly. 

We could also take this opportunity to support functions from other data warehouse providers (currently the functions are BQ-specific). Plus we could also take this opportunity to reinforce the use of style guide principles in those models.

┆Issue is synchronized with this [Jira Task](https://rittmananalytics.atlassian.net/browse/RADW-7) by [Unito](https://www.unito.io/learn-more)

**Comment by markrittman** [comment]
Done, and the current release uses cross-database functions as much as possible, and supports Snowflake DW as a target warehouse too.
